### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Sir-Will** [ProtocolSupport/ProtocolSupportLegacySupport#7]
This is with the latest build of ProtocolSupport from jenkins
```
[02:28:12] [Netty Server IO #1/ERROR]: Could not pass event ConnectionOpenEvent to ProtocolSupportLegacySupport v1.0
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: protocolsupport/api/Connection$PacketSendListener
	at protocolsupportlegacysupport.hologram.HologramHandler.initConnection(HologramHandler.java:39) ~[?:?]
	at protocolsupportlegacysupport.hologram.HologramHandler.onConnectionOpen(HologramHandler.java:34) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor29.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-510]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-510]
	at protocolsupport.protocol.pipeline.common.LogicHandler.channelActive(LogicHandler.java:81) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) ~[patched_1.13.2.jar:git-Paper-510]
	at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelActive(SimpleReadTimeoutHandler.java:27) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) ~[patched_1.13.2.jar:git-Paper-510]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.2.jar:git-Paper-510]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: protocolsupport/api/Connection$PacketSendListener
	... 44 more
Caused by: java.lang.ClassNotFoundException: protocolsupport.api.Connection$PacketSendListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-510]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-510]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	... 44 more
```

**Comment by matahombres** [comment]
https://www.spigotmc.org/resources/protocolsupportlegacysupport.44742/reviews
One user update 1.13.2
